title: Your awesome title
author: Alan-gao
email: 731607820@qq.com
copyright: Â© 2019 GitHub User
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

show_excerpts: false # set to true to show excerpts on the homepage

lin:
  date_format: "%b %-d, %Y"

  # path to the author avatar image
  avatar_path: assets/images/avatar.jpg

  # generate social links
  social_links:
    QQ: 731607820
    github:  Alan-gao

theme: lin

plugins:
 - jekyll-feed
 - jekyll-seo-tag
